.goreleaser.yml

This doesn't work for brew taps

Do not use templating in the binary name of the release

---

.goreleaser.yml

Release on [Snapcraft](https://snapcraft.io/).
See https://github.com/goreleaser/goreleaser/pull/1000 for adding the `bin_directory` option on the archive instead of setting it in the binary name.

 Release on Snapcraft 

---

.goreleaser.yml

The network interface is needed to communicate with the SecretHub API and the personal-files interface is needed to read/write the credential stored in `~/.secrethub`

 Request network and personal-files interfaces on the snap

---

.goreleaser.yml

- Move snap from `secrethub` to `secrethub-cli`
- Add the binary in a bin dir in the archive for windows (as was the case before v0.21.0)
- Request network access for the snap

Release v0.21.1

---

.goreleaser.yml

The CLI sometimes has to read from and write to files in the users
home directory, for example to read template files and to write
injected files to disk.

Goreleaser: request the home interface on snap

---

.goreleaser.yml

Use the same name for scoop as for other package managers.
This is also the name we have used in documentation.

Rename the scoop release to secrethub-cli

---

.goreleaser.yml

- Request the [home interface](https://docs.snapcraft.io/the-home-interface) on the snap release.
- Publish the scoop release as `secrethub-cli`

Release v0.21.2

---

README.md

Move around pieces of copy for a more coherent flow that works more
on a need-to-know basis than swamping the reader with text.

Make call to action in README clearer

---

README.md

This badge returns the status of the docs instead of a static,
always blue badge.

Use godoc status badge in the readme

---

internals/secrethub/app.go
internals/secrethub/audit.go

- Removed the hidden `audit repo` and `audit secret` commands
- Made `audit` a root command, which fixes the help text

Make audit a root command

---

internals/secrethub/run.go

This makes the default usage simpler.
The simple usecase should not require extra configuration. More complex projects that have multiple tempaltes, can configure them by supplying the flag.

Add a default to secrethub run --template

---

internals/secrethub/audit.go

The default command is executed when no command is supplied
(running secrethub without args in this case). This was used on
the audit command when it was a subcommand of audit. Now that
audit is a root command, we no longer want it to be the default.
Running secrethub without a command prints the help text.

Don't make audit the default command

---

internals/cli/masker/writer.go
internals/cli/masker/writer_test.go
internals/secrethub/run.go

Add secret masking functionality to `secrethub run`. By default all secrets will be masked in `stdout` and `stderr`. If these values are detected, they are replaced with `<redacted by SecretHub>`.
This can be disabled with the `--no-masking`-flag.
A separate goroutine with `MaskedWriter.Run()` is used to write masked content to the underlying `io.Writer`. This is done to support staggered writes: if a secret is long and is split over multiple calls to `Write()`, we still want to be able to mask these values. Therefore the goroutine with `MaskedWriter.Run()` waits for `Timeout` for any subsequent writes.
```
$ secrethub write path/to/secret
Please type in the value of the secret, followed by an [ENTER]:
$ secrethub run --envar TEST=path/to/secret -- printenv | grep TEST
TEST=<redacted by …
```

Mask secrets on stdout and stderr with secrethub run

---

cmd/secrethub/main.go

This is currently a noop as we no longer set a Sentry DSN. We do not track errors in the CLI.
`errio.CaptureErrorAndWait` was removed in [secrethub-go v0.19.0](https://github.com/secrethub/secrethub-go/pull/74). This change is required to update secrethub-go.

Remove remaining CaptureErrorAndWait

---

internals/secrethub/run.go
internals/secrethub/run_test.go

This work is based on #91 , please address that PR first.
Only allow letters, numbers and underscores in template var names and don't allow starting with a number.

 Only allow letters, numbers and underscores in template var names 

---

go.mod
go.sum
internals/cli/env_test.go
internals/secrethub/inject.go
internals/secrethub/run.go
internals/secrethub/run_test.go
internals/secrethub/secret_reader.go
internals/secrethub/tpl/errors.go
internals/secrethub/tpl/fakes/secret_reader.go
internals/secrethub/tpl/internal/token/token.go
internals/secrethub/tpl/template.go
internals/secrethub/tpl/v1.go
internals/secrethub/tpl/v2.go
internals/secrethub/tpl/v2_test.go

This fixes a bug where the closing of a template variable tag
just before the closing of a secret tag returned an error.
Example: {{path/to/secret/${var}}}
The secret templates are now parsed in one go instead of parsing
secret tags first and then parsing the contents of the tag to
look for variables.
The secret template parsing now returns richer error messages, that
include line- and column number where the error occured.
More validation on the contents of the secret- and variable tags
is done while parsing. These errors also include line- and column
number.
dollar signs ($) with a letter, digit or underscore following must
be escaped. This is so that we can add variable support without
brackets later ($var).
$, {, } and \ characters can now be escaped.
Lots of testcases for the parser …

Rework v2 secret templates

---

internals/secrethub/run.go
internals/secrethub/run_test.go

This makes the support similar to the [Node `dotenv` project](https://www.npmjs.com/package/dotenv#rules), which a lot of people are used to. The only feature we don't yet have is multiline support in quoted values, but we've decided to leave that for later. 
Also something to consider is how to handle quoted keys in the KEY=VALUE syntax. We can either pass them as is to the environment or ignore them and filter them out. IMO, passing them as is would be the simplest solution.

Add quote support to .ENV files

---

internals/secrethub/inject.go
internals/secrethub/run.go
internals/secrethub/run_test.go
internals/secrethub/template.go
internals/secrethub/tpl/template.go
internals/secrethub/tpl/template_test.go

- Undo breaking change of `v0.24.0`: Auto detect the template syntax version to use instead of defaulting to the new template syntax.

Release v0.24.1

---

internals/secrethub/run.go
internals/secrethub/run_test.go

Don't create a client in the run command when no secrets are used. Creating a client might prompt the user for their passphrase. We don't want to do that when it's not necessary.
Resolves #121

Lazily lookup credential in secrethub run

---

internals/cli/masker/writer_test.go

The current difference of 1ms between the sleep and the timeout
is sometimes not enough to process the write.
The processing of this write takes place in other goroutines and
is not finished when the sleep starts. When processing takes longer
than 1ms, the timeout does not kick in (as expected), because the
timeout is measured after processing of a write.
This should fix undeterministic failure of the test.

Increase sleep time in masked writer test

---

internals/secrethub/run.go
internals/secrethub/run_test.go
internals/secrethub/secret_reader.go

Resolves #131
This PR includes a fix for handling empty secret values, as secret masking could not handle those yet.

Add flag to the run command to suppress errors of non-existing secrets

---

go.mod
go.sum
internals/secrethub/service_ls.go
internals/secrethub/service_ls_test.go

The translation to columns is injected into the command, so that
we can use different columns in the service aws ls command, which
will be added later.

 Add type to service ls command 

---

internals/secrethub/org_init.go
internals/secrethub/service_init.go

Use `description` as the flag in the help-text and add aliases `descr` and `desc`.

Rename description flags and add aliasses

---

.goreleaser.yml

- Version and commit are now correctly shown when using `secrethub --version`.

v0.26.1: fix version and commit in CLI not being set

---

internals/secrethub/repo_invite.go
internals/secrethub/repo_invite_test.go

Only when prompting for confirmation we need extra information to
display. In other cases, we don't need to fetch the extra user
details.

Don't fetch the user in repo invite when not using it

---

internals/cli/masker/writer.go
internals/cli/masker/writer_test.go

For some inputs, the masking completely garbled the output. For example `secrethub run -- terraform plan` lead to unreadable output.
The cause of this was a wrong implementation of the `io.Writer` interface by `MaskedWriter`. It assumed control of the `[]byte` it takes as input, but it is not allowed to do so. 
The problem is demonstrated in the new `TestNewMaskedWriter/reuse_input_buffer` test.

Fix masking problem

---

internals/secrethub/acl_check.go
internals/secrethub/acl_check_test.go

- Return effective access rule on the directory instead of the
access rule set on the given directory. This fixes an error being
returned for a subdirectory on which no access is set. And it fixes
that the correct access level is returned when the account has a
higher access level on an ancestor directory.
- Return `none` when the account has no access.

Fix acl check on a specific account

---

internals/secrethub/repo_ls.go
internals/secrethub/repo_ls_test.go

We can later alias the `ls <workspace>` command to this command.

Add optional argument to repo ls to limit results to repos within a workspace

---

internals/secrethub/account_init.go
internals/secrethub/signup.go

This sets up a repository and writes the first secret on signup,
so that the user can start by reading their first secret. This is
intended to smoothen onboarding of new users.
Also, we no longer print the email address should be validated first,
as we have moved this constraint to the moment when users start
collaborating (org invite).

Create a start repository on signup

---

internals/cli/env.go

Use `SECRETHUB_<management command>_<command>_<flag>` as envvar
for subcommands, instead of using `SECRETHUB_<command>_<flag>`.

Use full command in flag envvars for subcommands

---

go.mod
go.sum
internals/secrethub/generate.go
internals/secrethub/generate_test.go
internals/secrethub/templates.go

New: `generate [--length=<length>] <path>`
Old: `generate rand <path> [<length>]` still works.

 Rename generate rand to generate and make length a flag 

---

.goreleaser.yml
scripts/post-install.sh
scripts/post-remove.sh

Especially the `.rpm` is handy for AWS. Allows us to do the following for installing on AWS Linux AMI:
```
yum install -y https://github.com/secrethub/secrethub-cli/releases/latest/download/secrethub-cli-amd64.rpm
```

Add nfpms to build .deb and .rpm packages

---

internals/secrethub/generate.go

This reverts commit b4d053a, reversing changes made to ed687d2.
We won't rename this flag right now, as we want to rename it to `--include symbols`.
See #177 for details on this plan.

Revert rename generate --symbols

---

internals/cli/masker/writer.go
internals/cli/masker/writer_test.go

There was a bug in MaskedWriter where it was only flushed on a timeout when a secret was found in the middle of a write. The reason was that `matchInProgress := false` had to be inside the loop instead of outside. Also added a test to test whether the problem is solved.

Fix bug MaskedWriter is not flushed before timeout

---

.goreleaser.yml

Because the automatically generated value is no good when using multiple
builds.

Explicitly set brew install field

---

internals/secrethub/write.go
internals/secrethub/write_test.go

Write the contents of a file to a secret with the --in-file flag.
Resolves #35

Add --in-file option to write command

---

internals/secrethub/read.go

Use --out-file (and --file-mode) to write the contents of a secret directly to a file.

Add --out-file and --file-mode flags to read

---

internals/secrethub/inject.go
internals/secrethub/run.go
internals/secrethub/run_test.go

On Windows the environment can contain key-value pair that is not valid
according to the standard. Run and inject used to fail on this because
they try to validate every individual key in the environment. When one
is incorrect, they error. E.g., I encountered the following line in
os.Environ() on Windows: =::=::\
This commits fixes this problem by ignoring any invalid lines in the
environment for injection purposes, but appending them to the
environment of the child process in case of a run.

Fix run and inject when env contains invalid value

---

.circleci/config.yml

This makes the logs of the job easier to read. You can easily see
whether downloading the deps succeeded and can check out the test
logs separately, without having the logs of downloading the deps.

Make downloading deps a separate CI step

---

internals/cli/ui/ask.go
internals/cli/ui/io.go
internals/cli/ui/io_unix.go
internals/cli/ui/io_windows.go
internals/secrethub/write.go

If `secrethub write --multiline` or `secrethub write -m` is used, the CLI will keep on asking for input until an `EOF` is reached. This can be triggered by the user pressing `CTRL+D` (which is the same). 
```
$ secrethub write --multiline org/repo/secret
Please type in the value of the secret, followed by [CTRL+D]:
user types
a multiline
secret
```
This flag is not allowed together with `--in-file` or `--clip`.

Add --multiline flag to write command

---

.goreleaser.yml

This should resolve the problem of the CLI not being able to contact the server when a .deb is installed in the ubuntu Docker image.

Release to develop

---

go.mod
go.sum
internals/cli/ui/ask.go
internals/cli/ui/ask_test.go
internals/secrethub/credential_backup.go
internals/secrethub/init.go

This adds a prompt for the name of the new credential when using `secrethub init` with a backup code:
```
./secrethub init --backup-code 234555352444233cdcd919d0a2a9d82eaa999e7ac800e8fb9bb71fc774a1d8b23
This backup code can be used to recover the account `my-account`
Do you want to continue? [Y/n]: 
What is the name of this device? [coffee-please] 
```
By default, the hostname of the current machine is suggested. For most people, this should suffice.
On signup, this does not add a name to the credential yet because this is a breaking change. Furthermore, it degrades the experience of the signup because we ask another question. We can later add this or implement a feature add a name to a credential that does not have one yet. We should be careful with allowing renames, as this could make …

Suggest credential name

---

internals/secrethub/service_aws_init.go

Tiny dev-x improvement. Can remove a `service ls` step in certain guides.

Print service ID when creating AWS service

---

internals/cli/env.go

CheckStrictEnv checks that every environment variable that starts with the app name is recognized by the application.

Add CheckStrictEnv func to cli.App

---

internals/secrethub/acl_check.go

When a secret path is supplied on acl check, return the effective permissions of the directory that contains the secret. As permissions reside only on directories, this is also the effective permission of the secret itself.

Accept secret paths on acl check

---

internals/secrethub/run.go

The CLI will return errors similar to these, when template parsing fails for any reason:
Encountered an error: error while parsing template file 'e1.env': could not parse template at line 1: template is not formatted as key=value pairs (run.invalid_template)  (run.template_file_parsing_failed) 
Encountered an error: error while parsing template file 'e2.env': no value was supplied for template variable 'env' (template.template_var_not_found)  (run.template_file_parsing_failed) 
Encountered an error: error while parsing template file 'e3.env': Secret not found (server.secret_not_found)  (run.template_file_parsing_failed) 
Encountered an error: error while parsing template file 'e4.env': template syntax error at 1:9: expected the closing of a secret tag `}}`, but reached the end of the …

Rephrase template processing error

---

.circleci/config.yml
go.mod

This makes it possible to use go 1.13 functionality. That does also mean, that at least go 1.13 is needed to build from source.
This is required for https://github.com/secrethub/secrethub-cli/pull/239

Use go 1.13

---

internals/secrethub/run.go
internals/secrethub/run_test.go

To increase testability, the `secrethub run` command's code will be refactored.
In order to decrease the risk of introducing new bugs during this procedure, some temporary tests have been added that verify most of the main functionality of the command.
These tests will be rewritten after the refactor, to better follow testing guidelines.

Add temporary tests to run command

---

.goreleaser.yml

Due to issues with sandboxed nature of snap and because we now have better deb/apt support, we've chosen to no longer release to snap.

Don't release to snapcraft

---

.circleci/config.yml
.goreleaser.yml

The old name_template is deprecated in favor of new file_name_template
field.
See: https://goreleaser.com/deprecations/#nfpms-name-template

Rename deprecated nfpms.name_template field

---

go.mod
go.sum

This solves two problems with autocompletion:
1. Users no longer get a panic when autocompleting a command after  `secrethub run --`.
2. After `secrethub run --` users no longer get suggestions for secrethub flags when trying to autocomplete a flag.

Update kingpin to latest

---

internals/cli/ui/ask.go
internals/cli/ui/io.go
internals/cli/ui/io_unix.go
internals/cli/ui/testing.go
internals/secrethub/inject.go
internals/secrethub/service_deploy_winrm.go
internals/secrethub/write.go
internals/secrethub/write_test.go

Reverts secrethub/secrethub-cli#274
This is needed for #269, but introduced a bug, see #277. For reverting this for now. So we can make a release.

Revert "Refactor ui package"

---

internals/secrethub/client_factory.go
internals/secrethub/client_factory_test.go

Allows a user to set the `SECRETHUB_PROXY_ADDRESS` environment variable or `--proxy-address` flag to configure a proxy used when connecting to the API. It allows for more precise control than just using the `HTTP_PROXY` environment variable because this only affects the SecretHub CLI.

Make proxy for HTTP-client configurable through flag

---

internals/secrethub/client_factory.go
internals/secrethub/service_gcp.go

This functionality is moving to GA. So no need to hide it any longer.

Unhide GCP IdP functionality

---

internals/secrethub/service_aws_init.go
internals/secrethub/service_gcp_init.go

Currently, when a service account for AWS or GCP cannot be created because the role/email has already been taken, the server returns a generic `ErrCredentialAlreadyExists` and the error gets converted to a more helpful error on the CLI-side.
This PR moves this responsibility to the server, so the error is nice and consistent in the other SecretHub clients too.

Move taken service account error to server

---

internals/secrethub/service_gcp_init.go

This avoids an annoying error at the end if the repo does not exist.

Directly check if repo exists

---

go.mod
go.sum
internals/secrethub/service_gcp_init.go

Other Service Accounts are not supported anyway, so no reason to list them.

Only list user-managed GCP Service Accounts in service gcp init prompt

---

internals/secrethub/service_init.go

Just like we already do for `service aws init`, don't accept a directory as argument of the command. Instead, if you want to set a permission on a subdirectory, you should use the `--permission` flag.

Do not accept a directory as argument to service init

---

internals/secrethub/env.go
internals/secrethub/env_ls.go
internals/secrethub/env_read.go
internals/secrethub/env_source.go
internals/secrethub/env_source_test.go
internals/secrethub/run.go
internals/secrethub/run_test.go

This PR adds the feature of passing all secrets under a given path to the child process of the run command. This path can be specified with the `--secrets-dir` flag.
I took the following decisions:
1. Environment variables set by this flag have priority over os environment variables, but have a lower precedence than the ones set through `.env` files.
2. In case of name collisions such as when there is a secret under the path: 
`namespace/repo/dir/db_username`
and one under the path:
`namespace/repo/dir/db/username`,
an error will be returned.
This was done because spotting such a name conflict can be difficult and choosing one value over the other can lead to unexpected results.
The naming collision error message and the help text of the flag might need some tweaking.

Map all secrets from directory to environment variables

---

internals/cli/masker/stream.go

The `indexedBuffer` was not goroutine safe, as the `upToIndex` method returned the result of `bytes.Buffer.Next`, which is a slice of the underlying buffer. This slice, according to the [documentation](https://golang.org/pkg/bytes/#Buffer.Next), is only valid until the next read or write operation on the buffer.
Therefore it might happen that after calling `upToIndex` but before using the value it returns, another goroutine writes to the buffer and invalidates the result of `upToIndex`.
This issue can also cause a data race, as the access to the underlying buffer through the result of `upToIndex` is not guarded with a mutex.
This PR fixes the issue by updating the `upToIndex` method to directly write these bytes to a writer, thus ensuring that any access to the underlying buffer is …

Fix masker data race

---

internals/secrethub/tree.go
internals/secrethub/tree_test.go

This PR contains the implementation of 3 flags for the `tree` command in the CLI:
- `-f` for full path of the directories and secrets
- `-i` for no indentation
- `--no-report` for skipping the report at the end

Add `-f`, `-i` and `--noreport` flags to tree command

---

internals/secrethub/acl_list_test.go

This PR contains an extra test case for the `acl ls` command: when getTree gets an error

Add getTree error case for 'acl ls' command

---

internals/secrethub/generate_test.go

This PR contains one extra test in which the clipboard is selected as the output

Include test case for clipboard for the 'secrethub generate' command

---

internals/secrethub/init.go

There is no valid use case where a user would have to enter it manually,
so we can better remove this altogehter and direct users to the website.

Remove prompt for setup code

---

internals/secrethub/env_source.go
internals/secrethub/env_source_test.go

Success on the executing order of a range over a map. As the order for looping of maps is undetermined, the test result was also undetermined.
By first performing a sort in the test, the result is no longer dependent, the assertion no succeeds indepedently of the executing within this loop.

Hotfix: fix test failing 50% of times

---

internals/secrethub/env_source.go

It did not explicitly say what happened with all secrets in the directory. Now it explicitly mentions that they are used as environment variables.

Clarify help of --secrets-dir

---

internals/secrethub/config.go
internals/secrethub/credential.go
internals/secrethub/credential_update_passphrase.go

Now that we have a `credential` management command, I believe it's more intuitive to group `update-passphrase` in there as well. What do you think?
This deprecates `secrethub config update-passphrase` command, in favor of `secrethub credential update-passphrase`.

Move update-passphrase command to "credential" management command

---

go.mod
go.sum
internals/secrethub/client_factory.go
internals/secrethub/credential_store.go

This PR, in combination with https://github.com/secrethub/secrethub-go/pull/223 ensures that all credential related errors are wrapped with a message that includes the source of the credential (except if the credential is passed via a cli flag).

Improve credential errors

---

internals/cli/env.go
internals/demo/command.go
internals/secrethub/app.go
internals/secrethub/client_factory.go
internals/secrethub/color.go
internals/secrethub/credential_store.go
internals/secrethub/debug.go
internals/secrethub/mlock.go

This PR adds a pre-run hook to all cobra commands that sets all unset flags to their corresponding environment variable's value. This also works in the case of persistent flags.
This PR introduces the limitation of registering all persistent flags on the root command.

Allow configuring flags from env vars

---

internals/secrethub/completion.go
scripts/post-install.sh

This PR contains a small fix which will replace the completion script from kingpin to the one provided by cobra for `.deb` and `.rpm` packages. In this way, the error of `unknown flag` visible in bash will be solved.

Replace completion flag from kingpin with cobra's completion command

---

internals/secrethub/account_inspect.go
internals/secrethub/account_inspect_test.go

This PR makes the `secrethub account inspect` command work for service accounts. The output of the command is extended to allow for easier parsing. The following fields are outputted:
for services:
- CreatedAt
- Description
- AccountType
- AccountName
- PublicAccountKey
for users:
- Username
- FullName
- Email
- EmailVerified
- CreatedAt
- AccountType
- AccountName
- PublicAccountKey

account inspect for service accounts

---

internals/secrethub/credential_store.go

The previous error message was solely focused on setting up a credential for a human. This new error message attempts to cover  both the human and service account use-case.

Improve credential not found error for service accounts

---

internals/secrethub/migrate.go

Before the migration tool would fail if the path was not valid. Sometimes, the path is valid (e.g. a repo), however the user does not have any permissions set for that specific repo, even though they are a member of the organization owning the repo.
Now the migration tool will just skip it with a warning.

Skip path if the person in org does not have any permissions

---

internals/secrethub/clear_clipboard.go
internals/secrethub/clear_clipboard_test.go
internals/secrethub/generate.go
internals/secrethub/generate_test.go
internals/secrethub/inject.go
internals/secrethub/read.go
internals/secrethub/read_test.go
internals/secrethub/service_init.go

`WriteClipboardAutoClear` spawns up a process to clear the clipboard, using the args of the current process as the base command. For tests, this caused the test command to be spawned, recursively spawning more test commands.
We somehow got away with this for a very long while, probably because the test executes quickly enough to exit before the stack runs full with processes. However, recently an AUR installation failed because of this bug in the tests, as AUR installations run the tests on installation.
This commit fixes the issue by mocking the calls to `WriteClipboardAutoClear` in the tests and using a fake implementation instead, that doesn't spawn new processes.

Fix tests using WriteClipboardAutoClear

---

internals/secrethub/migrate.go

When you're done applying the secrets migration, a logical next step would be to migrate your integrations. Including the link in the  success message makes it easier to follow along with the migration process.

Add integration migration instructions to the apply success message

---

internals/onepassword/onepassword.go

API credential does not have any required fields and it fits better with most of the data stored in SecretHub.

Switch 1Password item category used in migration to API credential

---

internals/secrethub/migrate_config_envfile.go
internals/secrethub/migrate_config_references.go
internals/secrethub/migrate_config_templates.go
internals/secrethub/migrate_config_test.go

The command would throw an error because it did not have write permission for overwriting the provided file.

Fix `migrate config templates` command

---

internals/secrethub/migrate_config_envfile.go
internals/secrethub/migrate_config_templates.go
internals/secrethub/migrate_config_test.go

Now it is no longer enforced to have template formats with whitespaces between the path and the curly brackets, such as 
`{{ path/to/secrets }}`
Depends on #389

Enable migrating templates without whitespaces

---

internals/onepassword/cli_v1.go
internals/onepassword/cli_v2.go
internals/onepassword/client_v2.go
internals/onepassword/onepassword.go
internals/secrethub/migrate.go

Users who have the 1Password CLI 2 installed can now migrate from SecretHub to 1Password.
Note: When 1Password CLI 2 is used, it no longer adds the sign-in address in the `1password-migration-plan.yml` file and it will not check whether the address coincides with the one the user is singed in.

Add support for 1Password CLI 2 in the migration
