secrethub/secrethub-cli

README.md

I removed all installation instructions and refer to website docs instead.

Restructure README and add usage section

---

go.mod
go.sum

 Update secrethub-go to v0.20.0

---

.goreleaser.yml

Add linux arm builds

---

internals/secrethub/inject.go
internals/secrethub/run.go
internals/secrethub/run_test.go
internals/secrethub/tpl/template.go
internals/secrethub/tpl/template_test.go
internals/secrethub/tpl/v1.go
internals/secrethub/tpl/v2.go
internals/secrethub/tpl/v2_test.go

This work continued on the work of #90 .
Please address that PR before reviewing this one.

 Add support for template vars to the run command 

---

internals/cli/env.go
internals/cli/env_test.go
internals/secrethub/app.go
internals/secrethub/run.go

This work is based on #92, please address that PR first.

 Set template variables using environment variables 

---

internals/secrethub/inject.go

 Add an in-file flag to inject 

---

internals/secrethub/org_init.go
internals/secrethub/service_aws_init.go
internals/secrethub/service_init.go

#141, now also for the `service aws init` command.

Rename description flags and add aliasses

---

internals/secrethub/service_aws_init.go

This is used when no region is set in the aws configuration or with
the --region flag.
If the KMS key is not given as an ARN, the user will still be prompted
for the region.

Use the region from the KMS key ARN when creating AWS services

---

internals/secrethub/generate.go
internals/secrethub/generate_test.go

Make generate command less verbose

---

internals/demo/app/page.go
internals/demo/app/serve.go

So it works locally and remotely.

Use relative url in demo app

---

.goreleaser.yml
scripts/post-install.sh
scripts/post-remove.sh

Some minor changes to `.goreleaser` to allow release to yum repository.

YUM release changes

---

internals/secrethub/read.go

Adds the `--no-newline, -n` flag, which, if set, prevents the command from outputting a newline character after the secret.

Add -n flag to read command to not print newline

---

go.mod
go.sum
internals/secrethub/account_inspect_test.go
internals/secrethub/acl_check_test.go
internals/secrethub/acl_list_test.go
internals/secrethub/acl_rm_test.go
internals/secrethub/acl_set_test.go
internals/secrethub/audit_repo_test.go
internals/secrethub/generate_test.go
internals/secrethub/inspect_secret_test.go
internals/secrethub/inspect_secret_version_test.go
internals/secrethub/mkdir_test.go
internals/secrethub/org_init_test.go
internals/secrethub/org_inspect_test.go
internals/secrethub/org_invite_test.go
internals/secrethub/org_list_users_test.go
internals/secrethub/org_ls_test.go
internals/secrethub/org_revoke_test.go
internals/secrethub/org_rm_test.go
internals/secrethub/org_set_role_test.go
internals/secrethub/repo_init_test.go
internals/secrethub/repo_inspect_test.go
internals/secrethub/repo_invite_test.go
internals/secrethub/repo_ls_test.go
internals/secrethub/repo_revoke_test.go
internals/secrethub/repo_rm_test.go
internals/secrethub/run_test.go
internals/secrethub/service_ls_test.go
internals/secrethub/write_test.go

Updated the tests after refactoring `fakeclient` in:
https://github.com/secrethub/secrethub-go/pull/176

Refactor tests to use fakeclient with funcs

---

README.md

Switch blurb to use secrets management

---

internals/demo/init.go

This PR makes the `secrethub demo init` command do nothing if it is executed on a repo which already contains a `username` and `password` secret and nothing else.

Make `secrethub demo init` do nothing on subsequent runs

---

go.mod
go.sum
internals/secrethub/credential_list_test.go

This PR contains the test suite for `credential ls` command

Testsuite for credential list

---

internals/secrethub/write_test.go

Hereby, a test suite that achieves 80% in statement coverage, compared to the 65% achieved before.

Extended test suite for the `secrethub write` CLI command.

---

internals/secrethub/app.go
internals/secrethub/read.go
internals/secrethub/read_test.go

This PR contains the necessary tests to ensure that the read command functions properly.
TO DO:

Test suite for read command

---

internals/secrethub/app.go
internals/secrethub/service_init.go
internals/secrethub/service_init_test.go

This PR contains the test suite for the service init command. One main focus will be whether the permissions are handled properly.

Test suite for service init with permissions

---

internals/cli/filemode/filemode.go

This line breaks compilation under go 1.15

Fix incorrect int to string conversion 

---

.gitignore

To prevent it from being committed as in this commit ec7fd122919b4bcd5159681e9b173123407e2802

Add secrethub binary to the gitignore

---

internals/secrethub/app.go
internals/secrethub/client_factory.go
internals/secrethub/client_factory_test.go
internals/secrethub/init.go

This is no longer necessary now that the signup command is removed.

Remove unauthenticated client

---

internals/onepassword/onepassword.go

The current version of the migration tool only looks for the 1Password config file on the path `~/.op/config`, this is, however a deprecated path, and the `op cli` uses other paths over this one, if possible.
The paths, ordered from lowest to highest priority are:
`~/.op/config`
`$XDG_CONFIG_HOME/config`
`~/config/.op`
`$XDG_CONFIG_HOME/op`
This PR fixes the issue, by using the same logic used by the `op cli` to determine the default config dir location.

Fix op config dir lookup
